apiVersion: apps/v1
kind: Deployment
metadata:
  name: humble-api-deployment
  labels:
    app: humble-api-pod
spec:
  selector:
    matchLabels:
      role: humble-api-pod
  template:
    metadata:
      labels:
        role: humble-api-pod
    spec:
      containers:
      - name: humble-api
        image: ziggoto/humble-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: humble-api
spec:
  selector:
    role: humble-api-pod
  type: LoadBalancer
  ports:
  - port: 3000
